[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; micro-ROS for PlatformIO
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit BNO08x
    adafruit/Adafruit BusIO

board_microros_transport = serial
board_microros_distro = humble
board_microros_packages = sensor_msgs geometry_msgs std_msgs nav_msgs
